name: Docker build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Image tag
        run: echo "TAG=${{ inputs.tag }}" >> "$GITHUB_ENV"
      - name: Lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: TAG=${{env.TAG}}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}:${{ env.TAG }}
          cache-to: type=inline
          tags: ghcr.io/${{ env.REPO }}:${{ env.TAG }}
